### ISSUE TITLE
Feature Request: Add New Language - PowerShell (Core?)

### ISSUE THREAD

**Issue by kenmaglio** [Codewars/codewars-runner-cli#456]
Hello, I'd love to see about getting PowerShell as part of Code Wars (even if it has to be PowerShell Core - that runs on Linux / Dockers).

I don't know the first thing about getting a new language added, but once it would be setup, I would love to contribute and our PowerShell User Group here in STL would add to it montly!

Please let me know - or community if any of you can help to get a "shell" of the language setup.  Thanks!!!!

**Comment by AnikaErceg** [comment]
Have you seen README.md fully? There is a section "How to add a new language?" so if you want to get your hands dirty, or speed up the process (or even learn something new), you could do it following those steps. :)

(Note that I haven't tried it myself, but it should give you a general idea of how it works.)

**Comment by kenmaglio** [comment]
Yes I have. 
However, building new docker images is something I'm not familiar with at all. 
And the very little documentation about runner script and spec -- made me post this.

I guess looking at other languages I could piece it together.

I was looking for someone who has started a new language and would be able to direct me / assist me - rather than trying to figure out everything on my own.

**Comment by kazk** [comment]
Is this duplicate of #192?
We should be able to add this following the [Ubuntu 14.04 installation instruction](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1404).

**Comment by kenmaglio** [comment]
Yes, it is. Sorry!

**Comment by kazk** [comment]
@kenmaglio 

No problem, maybe we should use this one to keep track of the progress since that issue got some spamming.

The hardest part of adding a language is tests. If you can provide information on how PowerShell code is tested, and if there're test frameworks allowing customizable output, that'll speed up the process significantly.

**Comment by kenmaglio** [comment]
@kazk 

There actually is a testing framework for PowerShell.
https://github.com/pester/Pester

So unit tests can be built pretty easily.

The open source PowerShell Core team, uses it to build / run tests on PowerShell Core itself. 
https://github.com/PowerShell/PowerShell-Tests

**Comment by kazk** [comment]
Thanks for the info.
Pester looks good. Can we customize the output format?
This is required in order to enable code challenges on Codewars.
You can see more information about it [here](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/output_format.md).

**Comment by PowerSchill** [comment]
I am working on getting a suitable docker image created. Then I will see what I can do to get pester configured.

**Comment by PowerSchill** [comment]
I was able to get everything working and almost ready for a PR. However is there any documentation on the format of the Examples file?

**Comment by kenmaglio** [comment]
Dude, you're awesome!

**Comment by kazk** [comment]
@PowerSchill 
Nice!
I couldn't find the documentation, but it should look like the following:

```yaml
# examples/powershell.yml
# test framework name
pester:
  # some name, other images uses "fundamentals", "algorithms", "bug fixes", "refactoring", etc.
  fundamentals:
    # starting point, what user sees when they open the challenge
    initital: ""
    # correct solution (opts.solution)
    answer: ""
    # tests (opts.fixture)
    fixture: ""
  algorithms:
    initital: ""
    answer: ""
    fixture: ""
```

Then add the following to `test/runners/powershell_spec.js` to make sure the examples work:

```js
runner.assertCodeExamples('powershell');
```
