### ISSUE TITLE
Add Lean v3.18.4

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars-runner-cli#828]
Please complete the following information:

- Name: Lean
- Version: [3.18.2](https://github.com/leanprover-community/lean/releases/tag/v3.18.2)

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
I need some up to date example code for testing. [Passing example with allowed axioms](https://github.com/DonaldKellett/CW-Lean3-Examples/blob/master/kata3/Solution.lean) doesn't work any more because of

```
unknown identifier 'add_comm'
state:
n m : ℕ
⊢ n + m = m + n
```

For something that uses `mathlib`, I've been using [this solution](https://www.codewars.com/kata/reviews/5ea44a10a52d7e00015ee8be/groups/5ea4a7479de752000120c26c), but it doesn't work any more because of

```
/workspace/_target/deps/mathlib/src/meta/expr.lean:446:9
invalid definition, a declaration named 'expr.pi_arity' has already been declared
```

I'm using the following `leanpkg.toml`:
```toml
[package]
name = "lean-challenge"
version = "1.0"
lean_version = "leanprover-community/lean:3.18.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e14ba7b059d149c69489d59003cae175ac45b24c"}
```
